#!/bin/bash

# Load environment variables (required because cron does not inherit the container's env)
if [ -f /etc/environment ]; then
  set -a
  source /etc/environment
  set +a
fi

WOOB_ACCOUNT_ID="${WOOB_ACCOUNT_ID:?WOOB_ACCOUNT_ID is required}"
WOOB_HISTORY_COUNT="${WOOB_HISTORY_COUNT:-200}"
OUTPUT_FILENAME="${OUTPUT_FILENAME:-bank_export.ofx}"
OUTPUT_PATH="/data/${OUTPUT_FILENAME}"

echo "[$(date)] Fetching transactions for account ${WOOB_ACCOUNT_ID}..."

woob config update

woob bank history "${WOOB_ACCOUNT_ID}" -f ofx -n "${WOOB_HISTORY_COUNT}" > "${OUTPUT_PATH}"

if [ -s "${OUTPUT_PATH}" ]; then
    echo "[$(date)] File successfully exported to ${OUTPUT_PATH}"
else
    echo "[$(date)] Error: file is empty or could not be generated by Woob."
    exit 1
fi
